### ISSUE TITLE
Switch to protobuf.js 6.0

### ISSUE THREAD

**Issue by cyraxx** [cyraxx/node-pogo-protos#11]
protobuf.js 6.0 should not only make our packed fields bugfix unnecessary but also features automatic TypeScript generation. There are some API changes however so it needs to be evaluated whether this would make additional changes in pogobuf and others necessary.

**Comment by likerRr** [comment]
@cyraxx hi, I updated the original repo of [`npp2ts`](https://github.com/likerRr/npp2ts) for better support of 5th version of `protobuf`. 

I reviewed generated typings for TypeScript in 6th version of `protobuf` and that looks great:
`pbjs -t static-module proto/POGOProtos.proto | pbts -o POGOProtos.d.ts -`

Works like a charm and generated typings are good enought :smile: 

You can get rid of `npp2ts` when you migrate to the 6th version.

**Comment by cyraxx** [comment]
Good to know, thanks for checking.
Someone is already working on protobuf.js 6 integration.

**Comment by cyraxx** [comment]
Closing all issues as this repository is no longer being maintained. See README for further information.
