### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by davidgwking** [cyraxx/node-pogo-protos#12]
https://github.com/cyraxx/node-pogo-protos/commit/010b5465e49b363ae54195dfa167f1420d3dc820

Please release master. The above commit contains a typings bug fix. In the previous version, Envelopes.UnknownMessage was not included.

**Comment by cyraxx** [comment]
Usually node-pogo-protos follows POGOProtos releases but there hasn't been one in a while so I went ahead and published 2.7.1.

**Comment by davidgwking** [comment]
Thank you! @cyraxx
