### ISSUE TITLE
Stardust inventory and pokemon_caught_by_type

### ISSUE THREAD

**Issue by sp00x** [cyraxx/node-pogo-protos#6]
When getting the inventory, how do I read

1) the current stardust amount for the trainer
2) the "pokemon_caught_by_type" byte array

Are these still /*todo*/ or is there a way of reading these values?

**Comment by cyraxx** [comment]
Stardust is a form of currency and included in the `PlayerData.currencies` field.

How the `pokemon_caught_by_type` field works I'm not sure. You might want to open an issue in the [POGOProtos repository](https://github.com/AeonLucid/POGOProtos).

**Comment by Vankxr** [comment]
PROFILE_RESPONSE_DECODED.player_data.currencies[0] --> Pokecoins
PROFILE_RESPONSE_DECODED.player_data.currencies[1] --> Stardust

**Comment by sp00x** [comment]
@Vankxr @cyraxx Aah, thanks for the currencies pointer - I had ignored that one!

I'll go hunt further for the pokemon_caught_by_type info.

**Comment by tegob** [comment]
@sp00x Did you ever figure out how to decode `pokemon_caught_by_type`?

**Comment by sp00x** [comment]
@tegob : I think I did an update on the pogoprotos package and got some array instead of the buffer, but it wasn't really clear to me what that array was: it seemed to not be 151 long - it's variable length, and rather short, so it wasn't apparent which pokemon the numbers in the array were referring to. Also, the raw buffer length is much larger than this array would seem to imply, so I figured it was wrong anyway... So I didn't look more at this :)
